/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface CrosschainCoinRouterInterface extends utils.Interface {
  contractName: "CrosschainCoinRouter";
  functions: {
    "cerc20()": FunctionFragment;
    "resetAllowance()": FunctionFragment;
    "swapCoinForCrosschainCoin(uint256)": FunctionFragment;
    "swapCoinForWrappedCoin(uint256)": FunctionFragment;
    "swapCrosschainCoinForCoin(uint256)": FunctionFragment;
    "swapCrosschainCoinForWrappedCoin(uint256)": FunctionFragment;
    "swapWrappedCoinForCoin(uint256)": FunctionFragment;
    "swapWrappedCoinForCrosschainCoin(uint256)": FunctionFragment;
    "wrappedCoin()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "cerc20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resetAllowance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapCoinForCrosschainCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCoinForWrappedCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCrosschainCoinForCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCrosschainCoinForWrappedCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapWrappedCoinForCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapWrappedCoinForCrosschainCoin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedCoin",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cerc20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resetAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapCoinForCrosschainCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapCoinForWrappedCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapCrosschainCoinForCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapCrosschainCoinForWrappedCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapWrappedCoinForCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapWrappedCoinForCrosschainCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedCoin",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CrosschainCoinRouter extends BaseContract {
  contractName: "CrosschainCoinRouter";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CrosschainCoinRouterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cerc20(overrides?: CallOverrides): Promise<[string]>;

    resetAllowance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapCrosschainCoinForCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapCrosschainCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapWrappedCoinForCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapWrappedCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wrappedCoin(overrides?: CallOverrides): Promise<[string]>;
  };

  cerc20(overrides?: CallOverrides): Promise<string>;

  resetAllowance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapCoinForCrosschainCoin(
    _amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapCoinForWrappedCoin(
    _amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapCrosschainCoinForCoin(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapCrosschainCoinForWrappedCoin(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapWrappedCoinForCoin(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapWrappedCoinForCrosschainCoin(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wrappedCoin(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    cerc20(overrides?: CallOverrides): Promise<string>;

    resetAllowance(overrides?: CallOverrides): Promise<void>;

    swapCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapCrosschainCoinForCoin(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapCrosschainCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapWrappedCoinForCoin(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapWrappedCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    wrappedCoin(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    cerc20(overrides?: CallOverrides): Promise<BigNumber>;

    resetAllowance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapCrosschainCoinForCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapCrosschainCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapWrappedCoinForCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapWrappedCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wrappedCoin(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cerc20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    resetAllowance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapCrosschainCoinForCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapCrosschainCoinForWrappedCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapWrappedCoinForCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapWrappedCoinForCrosschainCoin(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wrappedCoin(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
