/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ITubeInterface extends utils.Interface {
  contractName: "ITube";
  functions: {
    "depositNFTTo(uint256,address,uint256,address,bytes)": FunctionFragment;
    "depositTo(uint256,address,address,uint256,bytes)": FunctionFragment;
    "fees(uint256)": FunctionFragment;
    "lord()": FunctionFragment;
    "tubeToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositNFTTo",
    values: [BigNumberish, string, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTo",
    values: [BigNumberish, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "fees", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "lord", values?: undefined): string;
  encodeFunctionData(functionFragment: "tubeToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "depositNFTTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tubeToken", data: BytesLike): Result;

  events: {};
}

export interface ITube extends BaseContract {
  contractName: "ITube";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITubeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fees(
      _tubeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lord(overrides?: CallOverrides): Promise<[string]>;

    tubeToken(overrides?: CallOverrides): Promise<[string]>;
  };

  depositNFTTo(
    _tubeID: BigNumberish,
    _token: string,
    _tokenID: BigNumberish,
    _to: string,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositTo(
    _tubeID: BigNumberish,
    _token: string,
    _to: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fees(_tubeID: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  lord(overrides?: CallOverrides): Promise<string>;

  tubeToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    fees(_tubeID: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    lord(overrides?: CallOverrides): Promise<string>;

    tubeToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fees(_tubeID: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    lord(overrides?: CallOverrides): Promise<BigNumber>;

    tubeToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fees(
      _tubeID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lord(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tubeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
