/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TubeInterface extends utils.Interface {
  contractName: "Tube";
  functions: {
    "acceptOwnerships()": FunctionFragment;
    "concatKeys(bytes32[])": FunctionFragment;
    "count(uint256,address)": FunctionFragment;
    "counts(uint256,address)": FunctionFragment;
    "deposit(uint256,address,uint256,bytes)": FunctionFragment;
    "depositNFT(uint256,address,uint256,bytes)": FunctionFragment;
    "depositNFTTo(uint256,address,uint256,address,bytes)": FunctionFragment;
    "depositTo(uint256,address,address,uint256,bytes)": FunctionFragment;
    "fees(uint256)": FunctionFragment;
    "genKey(uint256,uint256,address,address,uint256,bytes)": FunctionFragment;
    "genKeyForNFT(uint256,uint256,address,uint256,address,bytes)": FunctionFragment;
    "isSettled(bytes32)": FunctionFragment;
    "ledger()": FunctionFragment;
    "lord()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "safe()": FunctionFragment;
    "setFee(uint256,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "tubeID()": FunctionFragment;
    "tubeToken()": FunctionFragment;
    "unpause()": FunctionFragment;
    "upgrade(address)": FunctionFragment;
    "verifier()": FunctionFragment;
    "withdraw(uint256,uint256,address,address,uint256,bytes,bytes)": FunctionFragment;
    "withdrawCoin(address)": FunctionFragment;
    "withdrawNFT(uint256,uint256,address,uint256,address,bytes,bytes)": FunctionFragment;
    "withdrawToken(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptOwnerships",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "concatKeys",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "count",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "counts",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNFT",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNFTTo",
    values: [BigNumberish, string, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositTo",
    values: [BigNumberish, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "fees", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "genKey",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "genKeyForNFT",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isSettled",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "ledger", values?: undefined): string;
  encodeFunctionData(functionFragment: "lord", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "safe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "tubeID", values?: undefined): string;
  encodeFunctionData(functionFragment: "tubeToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "upgrade", values: [string]): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCoin",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNFT",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnerships",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "concatKeys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "counts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositNFTTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "genKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "genKeyForNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSettled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ledger", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tubeID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tubeToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;

  events: {
    "NFTReceipt(uint256,address,uint256,uint256,address,address,bytes,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Receipt(uint256,address,uint256,address,address,uint256,bytes,uint256)": EventFragment;
    "Settled(bytes32,address[],bool)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NFTReceipt"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Receipt"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Settled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export type NFTReceiptEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, string, string, BigNumber],
  {
    tubeID: BigNumber;
    token: string;
    tokenID: BigNumber;
    txIdx: BigNumber;
    sender: string;
    recipient: string;
    data: string;
    fee: BigNumber;
  }
>;

export type NFTReceiptEventFilter = TypedEventFilter<NFTReceiptEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type PausedEvent = TypedEvent<[string], { account: string }>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export type ReceiptEvent = TypedEvent<
  [BigNumber, string, BigNumber, string, string, BigNumber, string, BigNumber],
  {
    tubeID: BigNumber;
    token: string;
    txIdx: BigNumber;
    sender: string;
    recipient: string;
    amount: BigNumber;
    data: string;
    fee: BigNumber;
  }
>;

export type ReceiptEventFilter = TypedEventFilter<ReceiptEvent>;

export type SettledEvent = TypedEvent<
  [string, string[], boolean],
  { key: string; validators: string[]; success: boolean }
>;

export type SettledEventFilter = TypedEventFilter<SettledEvent>;

export type UnpausedEvent = TypedEvent<[string], { account: string }>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface Tube extends BaseContract {
  contractName: "Tube";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TubeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnerships(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    concatKeys(keys: BytesLike[], overrides?: CallOverrides): Promise<[string]>;

    count(
      _tubeID: BigNumberish,
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    counts(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    deposit(
      _tubeID: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositNFT(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fees(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    genKey(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    genKeyForNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isSettled(key: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    ledger(overrides?: CallOverrides): Promise<[string]>;

    lord(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    safe(overrides?: CallOverrides): Promise<[string]>;

    setFee(
      _tubeID: BigNumberish,
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tubeID(overrides?: CallOverrides): Promise<[BigNumber]>;

    tubeToken(overrides?: CallOverrides): Promise<[string]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgrade(
      _newTube: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifier(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawCoin(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawToken(
      _to: string,
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnerships(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  concatKeys(keys: BytesLike[], overrides?: CallOverrides): Promise<string>;

  count(
    _tubeID: BigNumberish,
    _token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  counts(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deposit(
    _tubeID: BigNumberish,
    _token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositNFT(
    _tubeID: BigNumberish,
    _token: string,
    _tokenID: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositNFTTo(
    _tubeID: BigNumberish,
    _token: string,
    _tokenID: BigNumberish,
    _to: string,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositTo(
    _tubeID: BigNumberish,
    _token: string,
    _to: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fees(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  genKey(
    _srcTubeID: BigNumberish,
    _txIdx: BigNumberish,
    _token: string,
    _recipient: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  genKeyForNFT(
    _srcTubeID: BigNumberish,
    _txIdx: BigNumberish,
    _token: string,
    _tokenID: BigNumberish,
    _recipient: string,
    _data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  isSettled(key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  ledger(overrides?: CallOverrides): Promise<string>;

  lord(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  safe(overrides?: CallOverrides): Promise<string>;

  setFee(
    _tubeID: BigNumberish,
    _fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tubeID(overrides?: CallOverrides): Promise<BigNumber>;

  tubeToken(overrides?: CallOverrides): Promise<string>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgrade(
    _newTube: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifier(overrides?: CallOverrides): Promise<string>;

  withdraw(
    _srcTubeID: BigNumberish,
    _txIdx: BigNumberish,
    _token: string,
    _recipient: string,
    _amount: BigNumberish,
    _data: BytesLike,
    _signatures: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawCoin(
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawNFT(
    _srcTubeID: BigNumberish,
    _txIdx: BigNumberish,
    _token: string,
    _tokenID: BigNumberish,
    _recipient: string,
    _data: BytesLike,
    _signatures: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawToken(
    _to: string,
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnerships(overrides?: CallOverrides): Promise<void>;

    concatKeys(keys: BytesLike[], overrides?: CallOverrides): Promise<string>;

    count(
      _tubeID: BigNumberish,
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    counts(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      _tubeID: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositNFT(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    fees(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    genKey(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    genKeyForNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    isSettled(key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    ledger(overrides?: CallOverrides): Promise<string>;

    lord(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    safe(overrides?: CallOverrides): Promise<string>;

    setFee(
      _tubeID: BigNumberish,
      _fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tubeID(overrides?: CallOverrides): Promise<BigNumber>;

    tubeToken(overrides?: CallOverrides): Promise<string>;

    unpause(overrides?: CallOverrides): Promise<void>;

    upgrade(_newTube: string, overrides?: CallOverrides): Promise<void>;

    verifier(overrides?: CallOverrides): Promise<string>;

    withdraw(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawCoin(_to: string, overrides?: CallOverrides): Promise<void>;

    withdrawNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawToken(
      _to: string,
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NFTReceipt(uint256,address,uint256,uint256,address,address,bytes,uint256)"(
      tubeID?: BigNumberish | null,
      token?: string | null,
      tokenID?: BigNumberish | null,
      txIdx?: null,
      sender?: null,
      recipient?: null,
      data?: null,
      fee?: null
    ): NFTReceiptEventFilter;
    NFTReceipt(
      tubeID?: BigNumberish | null,
      token?: string | null,
      tokenID?: BigNumberish | null,
      txIdx?: null,
      sender?: null,
      recipient?: null,
      data?: null,
      fee?: null
    ): NFTReceiptEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Receipt(uint256,address,uint256,address,address,uint256,bytes,uint256)"(
      tubeID?: BigNumberish | null,
      token?: string | null,
      txIdx?: BigNumberish | null,
      sender?: null,
      recipient?: null,
      amount?: null,
      data?: null,
      fee?: null
    ): ReceiptEventFilter;
    Receipt(
      tubeID?: BigNumberish | null,
      token?: string | null,
      txIdx?: BigNumberish | null,
      sender?: null,
      recipient?: null,
      amount?: null,
      data?: null,
      fee?: null
    ): ReceiptEventFilter;

    "Settled(bytes32,address[],bool)"(
      key?: BytesLike | null,
      validators?: null,
      success?: null
    ): SettledEventFilter;
    Settled(
      key?: BytesLike | null,
      validators?: null,
      success?: null
    ): SettledEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    acceptOwnerships(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    concatKeys(
      keys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    count(
      _tubeID: BigNumberish,
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    counts(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      _tubeID: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositNFT(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fees(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    genKey(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    genKeyForNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSettled(key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    ledger(overrides?: CallOverrides): Promise<BigNumber>;

    lord(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    safe(overrides?: CallOverrides): Promise<BigNumber>;

    setFee(
      _tubeID: BigNumberish,
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tubeID(overrides?: CallOverrides): Promise<BigNumber>;

    tubeToken(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgrade(
      _newTube: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifier(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawCoin(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawToken(
      _to: string,
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnerships(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    concatKeys(
      keys: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    count(
      _tubeID: BigNumberish,
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    counts(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      _tubeID: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositNFT(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositNFTTo(
      _tubeID: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _to: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositTo(
      _tubeID: BigNumberish,
      _token: string,
      _to: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genKey(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    genKeyForNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSettled(
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ledger(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lord(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    safe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setFee(
      _tubeID: BigNumberish,
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tubeID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tubeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgrade(
      _newTube: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _recipient: string,
      _amount: BigNumberish,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawCoin(
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawNFT(
      _srcTubeID: BigNumberish,
      _txIdx: BigNumberish,
      _token: string,
      _tokenID: BigNumberish,
      _recipient: string,
      _data: BytesLike,
      _signatures: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawToken(
      _to: string,
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
