/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ValidatorRegistryInterface extends utils.Interface {
  contractName: "ValidatorRegistry";
  functions: {
    "files(address)": FunctionFragment;
    "getFile(address)": FunctionFragment;
    "register(uint256,string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "files", values: [string]): string;
  encodeFunctionData(functionFragment: "getFile", values: [string]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "files", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {};
}

export interface ValidatorRegistry extends BaseContract {
  contractName: "ValidatorRegistry";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ValidatorRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    files(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        validator: string;
        genre: BigNumber;
        uri: string;
      }
    >;

    getFile(
      _validator: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;

    register(
      genre: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  files(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string] & {
      validator: string;
      genre: BigNumber;
      uri: string;
    }
  >;

  getFile(
    _validator: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string]>;

  register(
    genre: BigNumberish,
    uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    files(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        validator: string;
        genre: BigNumber;
        uri: string;
      }
    >;

    getFile(
      _validator: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;

    register(
      genre: BigNumberish,
      uri: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    files(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getFile(_validator: string, overrides?: CallOverrides): Promise<BigNumber>;

    register(
      genre: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    files(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFile(
      _validator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      genre: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
