/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAllowlist, IAllowlistInterface } from "../IAllowlist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAllowlist__factory {
  static readonly abi = _abi;
  static createInterface(): IAllowlistInterface {
    return new utils.Interface(_abi) as IAllowlistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAllowlist {
    return new Contract(address, _abi, signerOrProvider) as IAllowlist;
  }
}
