/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBurnableERC20,
  IBurnableERC20Interface,
} from "../IBurnableERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "burnFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBurnableERC20__factory {
  static readonly abi = _abi;
  static createInterface(): IBurnableERC20Interface {
    return new utils.Interface(_abi) as IBurnableERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBurnableERC20 {
    return new Contract(address, _abi, signerOrProvider) as IBurnableERC20;
  }
}
