/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { WrappedCoin, WrappedCoinInterface } from "../WrappedCoin";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class WrappedCoin__factory {
  static readonly abi = _abi;
  static createInterface(): WrappedCoinInterface {
    return new utils.Interface(_abi) as WrappedCoinInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WrappedCoin {
    return new Contract(address, _abi, signerOrProvider) as WrappedCoin;
  }
}
