name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile
        run: yarn compile

      - name: Run unit tests
        run: yarn test